ignored_paths:
  - cmd/codecovgen
allowed_functions:
  - name: NewFactory
    classes:
      - provider
    return_types: [confmap.ProviderFactory]
  - name: NewFactory
    classes:
      - connector
    return_types: [connector.Factory]
  - name: NewFactory
    classes:
      - exporter
    return_types: [exporter.Factory]
  - name: NewFactory
    classes:
      - extension
    return_types: [extension.Factory]
  - name: NewFactory
    classes:
      - processor
    return_types: [processor.Factory]
  - name: NewFactory
    classes:
      - receiver
    return_types: [receiver.Factory]
  - name: NewFactory
    classes:
      - scraper
    return_types: [scraper.Factory]
  # Allow any functions under pkg
  - name: "*"
    classes:
      - pkg
  # Allow no functions under cmd
  - classes:
      - cmd

ignored_functions:
  - ^Test.*
  - ^Benchmark.*
  - ^Fuzz.*
  - ^Example.*

unkeyed_literal_initialization:
  enabled: true
  limit: 1 # this limit will increase over time to 5.
component_api: true
