// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the extension/usecase component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("usecase")
	ScopeName = "github.com/newrelic/nrdot-collector-components/extension/usecaseextension"
)

const (
	ExtensionStability = component.StabilityLevelAlpha
)
