extensions:
  usecase:
    usecase:
      value: "my-use-case"

receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      memory:
      load:
      filesystem:

processors:
  resourcedetection/env:
    detectors: [ "env" ]
    timeout: 2s
    override: true

exporters:
  otlphttp:
    endpoint: ${env:OTEL_EXPORTER_OTLP_ENDPOINT}
    headers:
      api-key: ${env:NEW_RELIC_LICENSE_KEY}
    auth:
      authenticator: usecase
  debug:
    verbosity: detailed

service:
  extensions: [usecase]
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [otlphttp, debug]
      processors: [resourcedetection/env]