// Copyright New Relic, Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mdatagen. DO NOT EDIT.

package newrelicoraclereceiver

import (
	"go.uber.org/goleak"
	"testing"
)

func TestMain(m *testing.M) {
	goleak.VerifyTestMain(m, goleak.IgnoreAnyFunction("github.com/cihub/seelog.(*asyncLoopLogger).processQueue"))
}
