// Copyright New Relic, Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("newrelicsqlserver")
	ScopeName = "github.com/newrelic/nrdot-collector-components/receiver/newrelicsqlserverreceiver"
)

const (
	LogsStability    = component.StabilityLevelDevelopment
	MetricsStability = component.StabilityLevelAlpha
)
