// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("usecase_setter")
	ScopeName = "github.com/newrelic/nrdot-collector-components/extension/usecasesetterextension"
)

const (
	ExtensionStability = component.StabilityLevelBeta
)
