name: Security Scan Daily Report - Database Receivers
on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


jobs:
  trivy-scan:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest
    env:
      TRIVY_DISABLE_VEX_NOTICE: "true"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v4
      
      - name: Run Trivy Scan - Oracle Receiver
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          scan-type: 'fs'
          scan-ref: 'receiver/newrelicoraclereceiver'
          format: 'table'
          ignore-unfixed: false
          severity: "CRITICAL,HIGH,MEDIUM,LOW"
          vuln-type: 'os,library'
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db
